/// <reference types="cypress" />

describe("Home page", () => {
    it("should display the correct title and meta tags", () => {
        cy.visit("/");
        cy.title().should("eq", "Home");
        cy.get('meta[name="description"]').should(
            "have.attr",
            "content",
            "Generated by create next app"
        );
        cy.get('meta[name="viewport"]').should(
            "have.attr",
            "content",
            "width=device-width, initial-scale=1"
        );
        cy.get('link[rel="icon"]').should("have.attr", "href", "/favicon.ico");
    });

    it("should display the navbar", () => {
        cy.visit("/");
        cy.get('[data-cy="navbar"]').should("exist");
    });

    it("should display the home page content", () => {
        cy.visit("/");
        cy.get("h1").should(
            "contain",
            "Experience the joy of finding your perfect home"
        );
        cy.get("button").should("contain", "Properties");
    });

    it("should navigate to the properties page when the properties button is clicked", () => {
        cy.visit("/");
        cy.get("button").click();
        cy.url().should("include", "/properties");
    });
});
