import { useSession, getSession } from "next-auth/react";
import NavBar from "../../components/NavBar";
import Head from "next/head";
import { NextPage } from "next";
import Link from "next/link";
import { GetServerSideProps } from "next";
import Background from "@/components/Backgrounds";

// Cancel page
const CancelPage: NextPage = () => {
    const { data: session } = useSession();

    // Render the cancel page
    return (
        <>
            <Head>
                <title>Cancel</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Background />
            <NavBar isLoggedIn={!!session} />
            <div className="container mx-auto p-5 pt-20 flex flex-col">
                <h1 className="text-4xl font-bold text-center mb-5">
                    Payment was cancelled!
                </h1>
                <p className="text-center text-lg">
                    Sorry for any inconvenience caused. Please try again.
                </p>
                <Link href="/" className="flex justify-center">
                    <button className="justify-center px-8 py-3 mt-44 bg-white bg-opacity-75 text-blue-500 font-bold text-3xl rounded-md hover:shadow-lg  hover:bg-blue-500 hover:text-white border-2 border-blue-500">
                        Back to Home
                    </button>
                </Link>
            </div>
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
    // Get the session
    const session = await getSession(context);

    // Check if the contract exists and if the logged-in user's email matches the email associated with the contract
    if (!session) {
        return {
            redirect: {
                destination: "/",
                permanent: false,
            },
        };
    }

    return {
        props: {},
    };
};

export default CancelPage;
