import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { getSession, useSession, signOut } from "next-auth/react";
import { FC } from "react";
import { NextApiRequest } from "next";
import NavBar from "../components/NavBar";
import Image from "next/image";

type Session = ReturnType<typeof useSession>["data"];
type SessionNoNull = NonNullable<Session>;

type sessionProps = {
    session: Session;
};

export default function Home() {
    const { data: session, status } = useSession();

    return (
        <>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="relative">
                <NavBar isLoggedIn={!!session} />

                <Image
                    src="/assets/interiordesign.jpg"
                    alt="Interior Design"
                    width="0"
                    height="0"
                    sizes="100vw"
                    className="w-full h-screen"
                />
                <div className="absolute top-52 left-0 w-full h-1/2 flex m-50 items-center justify-center z-0">
                    <h1 className="absolute top-28 text-center font-bold text-white text-4xl">
                        Experience the joy of finding your perfect home
                    </h1>
                    <Link href="/properties">
                        <button className="px-8 py-3 mt-44 bg-white bg-opacity-75 text-blue-500 font-bold text-3xl rounded-md hover:shadow-lg hover:bg-transparent hover:border-white hover:text-white border-2 border-blue-500">
                            Properties
                        </button>
                    </Link>
                </div>
            </div>
        </>
    );
}

// // Authorised User
// const User: FC<sessionProps> = ({ session }) => {

