import { ChangeEvent, FC } from "react";
import Head from "next/head";
import { useFormik } from "formik";
import { useEffect } from "react";
import { getSession, useSession, signOut } from "next-auth/react";
import NavBar from "../components/NavBar";
import Image from "next/image";
import Router from "next/router";

type Session = ReturnType<typeof useSession>["data"];
type SessionNoNull = NonNullable<Session>;

type sessionProps = {
    session: Session;
};

const Listing: FC<sessionProps> = () => {
    const { data: session, status } = useSession();
    let exteriorImage: string[] = [];
    let images: string[] = [];
    let floorPlans: string[] = [];

    const formik = useFormik({
        initialValues: {
            price: "",
            size: "",
            bedrooms: "",
            bathrooms: "",
            houseType: "",
            address: "",
            tenure: "",
            taxBand: "",
            rent: "",
            keyFeatures: "",
            description: "",
            contactNumber: "",
            contactEmail: "",
            exteriorImage: exteriorImage,
            images: images,
            floorPlan: floorPlans,
            email: session?.user?.email,
        },
        onSubmit: async (values) => {
            //call the createListing api
            fetch("/api/createListing", {
                method: "POST",
                body: JSON.stringify(values),
            });
            Router.push("/properties");
        },
    });

    useEffect(() => {
        formik.setValues((values) => ({
            ...values,
            email: session?.user?.email || "",
        }));
    }, [session?.user?.email]);

    function readFileAsText(file: File) {
        return new Promise(function (resolve, reject) {
            let fr = new FileReader();

            fr.onload = function () {
                resolve(fr.result);
            };

            fr.onerror = function () {
                reject(fr);
            };

            fr.readAsDataURL(file);
        });
    }

    async function encodeExteriorImage(e: ChangeEvent<HTMLInputElement>) {
        let files = e.target.files!;
        let readers = [];

        // Abort if there were no files selected
        if (!files.length) return;

        // Store promises in array
        for (let i = 0; i < files.length; i++) {
            readers.push(readFileAsText(files[i]));
        }

        // Trigger Promises
        Promise.all(readers).then((exteriorImage) => {
            // Values will be an array that contains an item
            // with the text of every selected file
            // ["File1 Content", "File2 Content" ... "FileN Content"]
            formik.setValues((values) => ({
                ...values,
                exteriorImage: exteriorImage as string[],
            }));
        });
    }


    async function encodeImage(e: ChangeEvent<HTMLInputElement>) {
        let files = e.target.files!;
        let readers = [];

        // Abort if there were no files selected
        if (!files.length) return;

        // Store promises in array
        for (let i = 0; i < files.length; i++) {
            readers.push(readFileAsText(files[i]));
        }

        // Trigger Promises
        Promise.all(readers).then((image) => {
            // Values will be an array that contains an item
            // with the text of every selected file
            // ["File1 Content", "File2 Content" ... "FileN Content"]
            formik.setValues((values) => ({
                ...values,
                images: image as string[],
            }));
        });
    }

    async function encodeFloorPlan(e: ChangeEvent<HTMLInputElement>) {
        let files = e.target.files!;
        let readers = [];

        // Abort if there were no files selected
        if (!files.length) return;

        // Store promises in array
        for (let i = 0; i < files.length; i++) {
            readers.push(readFileAsText(files[i]));
        }

        // Trigger Promises
        Promise.all(readers).then((floorPlan) => {
            // Values will be an array that contains an item
            // with the text of every selected file
            // ["File1 Content", "File2 Content" ... "FileN Content"]
            formik.setValues((values) => ({
                ...values,
                floorPlan: floorPlan as string[],
            }));
        });
    }

    return (
        <>
            <Head>
                <title>Listing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="relative">
                <NavBar isLoggedIn={!!session} />

                <Image
                    src="/assets/interiorform.jpg"
                    alt="Interior Design Form"
                    width="0"
                    height="0"
                    sizes="100vw"
                    className="w-full h-screen absolute -z-10"
                />
                <div className="w-full items-center justify-center flex flex-col pt-24">
                    <div className="p-5 w-3/6 bg-white rounded-lg shadow-lg flex flex-col items-center justify-center">
                        <div className="flex flex-col">
                            {/* Title */}
                            <h1 className="text-4xl font-bold text-center">
                                Create a new listing
                            </h1>

                            <section className="w-3/4 mx-auto flex flex-col">
                                {/* Form */}
                                <form
                                    className="mt-10 grid grid-cols-2 gap-y-5 gap-x-10"
                                    onSubmit={formik.handleSubmit}
                                >
                                    {/* Price */}
                                    <div className="flex flex-col">
                                        <label
                                            htmlFor="price"
                                            className="font-bold"
                                        >
                                            Price
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps("price")}
                                        />
                                    </div>

                                    {/* Bedrooms */}
                                    <div className="flex flex-col">
                                        <label htmlFor="bedrooms" className="font-bold">
                                            Bedrooms
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps(
                                                "bedrooms"
                                            )}
                                        />
                                    </div>

                                    {/* Bathrooms */}
                                    <div className="flex flex-col">
                                        <label htmlFor="bathrooms" className="font-bold">
                                            Bathrooms
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps(
                                                "bathrooms"
                                            )}
                                        />
                                    </div>

                                    {/* House Type */}
                                    <div className="flex flex-col">
                                        <label htmlFor="houseType" className="font-bold">
                                            House Type
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps(
                                                "houseType"
                                            )}
                                        />
                                    </div>

                                    {/* Address */}
                                    <div className="flex flex-col">
                                        <label htmlFor="address" className="font-bold">Address</label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps("address")}
                                        />
                                    </div>

                                    {/* Tenure */}
                                    <div className="flex flex-col">
                                        <label htmlFor="tenure" className="font-bold">Tenure</label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps("tenure")}
                                        />
                                    </div>

                                    {/* Tax Band */}
                                    <div className="flex flex-col">
                                        <label htmlFor="taxBand" className="font-bold">
                                            Tax Band
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps("taxBand")}
                                        />
                                    </div>

                                    {/* Rent */}
                                    <div className="flex flex-col">
                                        <label htmlFor="rent" className="font-bold">Rent</label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps("rent")}
                                        />
                                    </div>

                                    {/* Key Features */}
                                    <div className="flex flex-col">
                                        <label htmlFor="keyFeatures" className="font-bold">
                                            Key Features
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps(
                                                "keyFeatures"
                                            )}
                                        />
                                    </div>

                                    {/* Description */}
                                    <div className="flex flex-col">
                                        <label htmlFor="description" className="font-bold">
                                            Description
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps(
                                                "description"
                                            )}
                                        />
                                    </div>

                                    {/* Contact Number */}
                                    <div className="flex flex-col">
                                        <label htmlFor="contactNumber" className="font-bold">
                                            Contact Number
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps(
                                                "contactNumber"
                                            )}
                                        />
                                    </div>

                                    {/* Contact Email */}
                                    <div className="flex flex-col">
                                        <label htmlFor="contactEmail" className="font-bold">
                                            Contact Email
                                        </label>
                                        <input
                                            className="p-1 border rounded-lg bg-gray-50 border-gray-300 text-gray-900"
                                            type="text"
                                            {...formik.getFieldProps(
                                                "contactEmail"
                                            )}
                                        />
                                    </div>
                                    
                                    {/* Exterior Images */}
                                    <div className="flex flex-col">
                                        <label htmlFor="exteriorImage" className="font-bold">Exterior Image</label>
                                        <input
                                            type={"file"}
                                            accept={
                                                "image/png, image/jpg, image/jpeg"
                                            }
                                            className="relative m-0 block w-full min-w-0 flex-auto rounded border border-solid border-neutral-300 dark:border-neutral-600 bg-clip-padding py-[0.32rem] px-3 text-base font-normal text-neutral-700 dark:text-neutral-200 transition duration-300 ease-in-out file:-mx-3 file:-my-[0.32rem] file:overflow-hidden file:rounded-none file:border-0 file:border-solid file:border-inherit file:bg-neutral-100 dark:file:bg-neutral-700 file:px-3 file:py-[0.32rem] file:text-neutral-700 dark:file:text-neutral-100 file:transition file:duration-150 file:ease-in-out file:[margin-inline-end:0.75rem] file:[border-inline-end-width:1px] hover:file:bg-neutral-200 focus:border-primary focus:text-neutral-700 focus:shadow-[0_0_0_1px] focus:shadow-primary focus:outline-none"
                                            onChange={(e) => {
                                                encodeExteriorImage(e);
                                            }}
                                        />
                                    </div>


                                    {/* Images */}
                                    <div className="flex flex-col">
                                        <label htmlFor="images" className="font-bold">Images</label>
                                        <input
                                            type={"file"}
                                            accept={
                                                "image/png, image/jpg, image/jpeg"
                                            }
                                            multiple
                                            className="relative m-0 block w-full min-w-0 flex-auto rounded border border-solid border-neutral-300 dark:border-neutral-600 bg-clip-padding py-[0.32rem] px-3 text-base font-normal text-neutral-700 dark:text-neutral-200 transition duration-300 ease-in-out file:-mx-3 file:-my-[0.32rem] file:overflow-hidden file:rounded-none file:border-0 file:border-solid file:border-inherit file:bg-neutral-100 dark:file:bg-neutral-700 file:px-3 file:py-[0.32rem] file:text-neutral-700 dark:file:text-neutral-100 file:transition file:duration-150 file:ease-in-out file:[margin-inline-end:0.75rem] file:[border-inline-end-width:1px] hover:file:bg-neutral-200 focus:border-primary focus:text-neutral-700 focus:shadow-[0_0_0_1px] focus:shadow-primary focus:outline-none"
                                            onChange={(e) => {
                                                encodeImage(e);
                                            }}
                                        />
                                    </div>

                                    {/* Floor Plan */}
                                    <div className="flex flex-col">
                                        <label htmlFor="floorPlan" className="font-bold">
                                            Floor Plan
                                        </label>
                                        <input
                                            type={"file"}
                                            accept={
                                                "image/png, image/jpg, image/jpeg"
                                            }
                                            multiple
                                            className="relative m-0 block w-full min-w-0 flex-auto rounded border border-solid border-neutral-300 dark:border-neutral-600 bg-clip-padding py-[0.32rem] px-3 text-base font-normal text-neutral-700 dark:text-neutral-200 transition duration-300 ease-in-out file:-mx-3 file:-my-[0.32rem] file:overflow-hidden file:rounded-none file:border-0 file:border-solid file:border-inherit file:bg-neutral-100 dark:file:bg-neutral-700 file:px-3 file:py-[0.32rem] file:text-neutral-700 dark:file:text-neutral-100 file:transition file:duration-150 file:ease-in-out file:[margin-inline-end:0.75rem] file:[border-inline-end-width:1px] hover:file:bg-neutral-200 focus:border-primary focus:text-neutral-700 focus:shadow-[0_0_0_1px] focus:shadow-primary focus:outline-none"
                                            onChange={(e) => {
                                                encodeFloorPlan(e);
                                            }}
                                        />
                                    </div>

                                    {/* Submit */}
                                    <button
                                        className="p-4 col-span-2 border-blue-500 border-2 text-blue-500 hover:border-white hover:text-white hover:bg-blue-500 rounded-lg"
                                        type="submit"
                                    >
                                        Submit
                                    </button>
                                </form>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Listing;
