import Head from "next/head";
import Layout from "../layout/layout";
import { FC } from "react";
import Link from "next/link";
import styles from "../styles/Form.module.css";
import { HiAtSymbol } from "react-icons/hi";
import { FaLock } from "react-icons/fa";
import { useState } from "react";
import { signIn } from "next-auth/react";
import { useFormik } from "formik";
import { validateLogin } from "lib/validate";
import { useRouter } from "next/router";
import { GetServerSideProps } from "next";
import { getSession } from "next-auth/react";

// Login page
const Login: FC = () => {
    const [show, setShow] = useState(false);
    const router = useRouter();

    // Setup formik for form validation
    const formik = useFormik({
        initialValues: {
            email: "",
            password: "",
        },
        validate: validateLogin,
        onSubmit: async (values) => {
            // Sign in user
            const result = await signIn("credentials", {
                callbackUrl: "/",
                email: values.email,
                password: values.password,
            });

            if (result!.ok) {
                router.push(result!.url!);
            }
        },
    });

    // Render the login page
    return (
        <Layout>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="w-3/4 mx-auto flex flex-col gap-10">
                {/* Title */}
                <div className="title">
                    <h1 className="text-gray-800 text-4xl font-bold py-4">
                        Login
                    </h1>
                    <p className="w-3/4 mx-auto text-gray-400">
                        Explore homes that fit your lifestyle
                    </p>
                </div>

                {/* Form */}
                <form
                    className="flex flex-col gap-5"
                    onSubmit={formik.handleSubmit}
                >
                    {/* Email */}
                    <div
                        className={`${styles.input_group} ${
                            formik.errors.email && formik.touched.email
                                ? "border-red-600"
                                : ""
                        }`}
                    >
                        <input
                            className={styles.input_text}
                            type="email"
                            placeholder="email"
                            {...formik.getFieldProps("email")}
                        />
                        <span className="icon flex items-center px-4">
                            <HiAtSymbol size={25} />
                        </span>
                    </div>

                    {/* Password */}
                    <div
                        className={`${styles.input_group} ${
                            formik.errors.password && formik.touched.password
                                ? "border-red-600"
                                : ""
                        }`}
                    >
                        <input
                            className={styles.input_text}
                            type={show ? "text" : "password"}
                            placeholder="password"
                            {...formik.getFieldProps("password")}
                        />
                        <span
                            className="icon flex items-center px-4"
                            onClick={() => setShow(!show)}
                        >
                            <FaLock size={20} />
                        </span>
                    </div>

                    {/* {formik.touched.password && formik.errors.password ? (
                        <div className="text-red-500 text-sm">
                            {formik.errors.password}
                        </div>
                    ) : null} */}

                    {/* Login buttons */}
                    <div className="input-button">
                        <button className={styles.button} type="submit">
                            Login
                        </button>
                    </div>
                </form>

                <p className="text-center text-gray-400">
                    Dont have an account?{" "}
                    <Link href={"/register"} className="text-blue-700">
                        Sign Up
                    </Link>
                </p>
            </section>
        </Layout>
    );
};

// Get the offers and users for the property
export const getServerSideProps: GetServerSideProps = async (context) => {
    // Get the session
    const session = await getSession(context);

    // If the user is logged in, redirect to the home page
    if (session) {
        return {
            redirect: {
                destination: "/",
                permanent: false,
            },
        };
    }

    return {
        props: {},
    };
};

export default Login;
