import { GetServerSideProps, NextPage } from "next";
import { Property } from "@prisma/client";
import prisma from "../../prisma/prisma";
import Head from "next/head";
import { getSession, useSession, signOut } from "next-auth/react";
import NavBar from "@/components/NavBar";
import { useState } from "react";
import Background from "@/components/Backgrounds";
import { useFormik } from "formik";
import Router from "next/router";
import { ChangeEvent } from "react";
import FileUpload from "@/components/FileUpload";
import { useEffect } from "react";
import DisplayCard from '@/components/DisplayCard';
import MyListingCard from "@/components/MyListingCard";

interface PropertyProps {
    properties: Property[];
}

type Session = ReturnType<typeof useSession>["data"];
type SessionNoNull = NonNullable<Session>;

type sessionProps = {
    session: Session;
};

const MyListings: NextPage<PropertyProps> = ({ properties }) => {
    const { data: session, status } = useSession();

    return (
        <div>
            <Head>
                <title>My Listings</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Background />
            <NavBar isLoggedIn={!!session} />
            <div className = "p-5 pt-20">
                <h1 className = "text-4xl font-bold text-center mb-5">My Listings</h1>
                <MyListingCard properties = {properties} />
            </div>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
    const session = await getSession(context);
    
    // Get the user
    const user = await prisma.user.findUnique({
        where: {
            email: session?.user?.email!,
        },
    });

    // Get all properties that the user has created
    const properties = await prisma.property.findMany({
        where: {
            user: {
                email: user?.email,
            },
        },
    });

    return {
        props: {
            properties: JSON.parse(JSON.stringify(properties)),
        },
    };

}

export default MyListings;
