import React from 'react';
import prisma from "../../prisma/prisma";
import { NextPage } from 'next';
import { Property } from '@prisma/client';
import DisplayCard from '../components/DisplayCard';
import Head from 'next/head';
import NavBar from "../components/NavBar";
import { getSession, useSession, signOut } from "next-auth/react";
import Background from '../components/Backgrounds';

interface PropertyProps {
    properties: Property[];
}

type Session = ReturnType<typeof useSession>["data"];
type SessionNoNull = NonNullable<Session>;

type sessionProps = {
    session: Session;
};

const Properties: NextPage<PropertyProps> = ({ properties }) => {

    const { data: session, status } = useSession();

    return(
        <div>
            <Head>
                <title>Properties</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Background />
            <NavBar isLoggedIn={!!session} />
            <div className = "p-5 pt-20">
                <h1 className = "text-4xl font-bold text-center mb-5">Properties</h1>
                <DisplayCard properties = {properties} />
            </div>
        </div>
    )
};

export async function getServerSideProps() {
    const properties = await prisma.property.findMany();
    return {
        props: { properties: JSON.parse(JSON.stringify(properties)) },
    };
}

export default Properties;