import { getSession, useSession } from "next-auth/react";
import NavBar from "@/components/NavBar";
import Head from "next/head";
import Link from "next/link";
import { GetServerSideProps } from "next";
import prisma from "../../prisma/prisma";
import Background from "@/components/Backgrounds";
import { useRouter } from "next/router";

const VerifiedPage = () => {
    // Get the user session
    const { data: session } = useSession();
    const router = useRouter();

    // Get the user email
    const email = session?.user?.email;

    // Call the verificationCheck API
    if (session) {
        fetch("/api/verificationCheck", {
            method: "POST",
            body: JSON.stringify({
                email: email,
            }),
        })
            .then((res) => {
                console.log(res);
            })
            .catch((err) => {
                console.log(err);
            });
    }

    // Render the verified page
    return (
        <>
            <Head>
                <title>Verified</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Background />
            <NavBar isLoggedIn={!!session} />
            <div className="container mx-auto p-5 pt-20 flex flex-col">
                <h1 className="text-4xl font-bold text-center mb-5">
                    Verified!
                </h1>
                <p className="text-center text-lg">
                    Thank you for your verification
                </p>
                <Link href="/profile" className="flex justify-center">
                    <button className="justify-center px-8 py-3 mt-44 bg-white bg-opacity-75 text-blue-500 font-bold text-3xl rounded-md hover:shadow-lg  hover:bg-blue-500 hover:text-white border-2 border-blue-500">
                        Back to Profile
                    </button>
                </Link>
            </div>
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
    const session = await getSession(context);
    const email = session?.user?.email;

    // Get the contract ID from the URL query string
    const { id } = context.query;

    // Check if the user is logged in
    if (!session) {
        return {
            redirect: {
                destination: "/login",
                permanent: false,
            },
        };
    }

    // Get the user from the database
    const user = await prisma.user.findFirst({
        where: {
            email: email as string,
        },
    });

    return {
        props: {
            user: JSON.parse(JSON.stringify(user)),
        },
    };
};

export default VerifiedPage;
